from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet


def generate_prediction_report(
    file_path,
    churn_probability,
    prediction_label,
    risk_tier,
    primary_driver,
    retention_strategy
):
    doc = SimpleDocTemplate(
        file_path,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()
    story = []

    # Title
    story.append(
        Paragraph(
            "Customer Churn Prediction Report",
            styles["Title"]
        )
    )
    story.append(Spacer(1, 20))

    # Table data
    data = [
        ["Metric", "Value"],
        ["Churn Probability", f"{churn_probability * 100:.2f}%"],
        ["Predicted Outcome", prediction_label],
        ["Risk Tier", risk_tier],
        ["Primary Churn Driver", primary_driver],
        ["Retention Strategy", retention_strategy],
    ]

    table = Table(data, colWidths=[180, 340])

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563eb")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1),
             [colors.whitesmoke, colors.lightgrey]),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ])
    )

    story.append(table)
    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "Generated by the Customer Churn Intelligence Platform.",
            styles["Italic"]
        )
    )

    doc.build(story)