from utils.load_css import load_css

load_css()

import streamlit as st

# =========================================================
# PAGE CONFIGURATION
# =========================================================
st.set_page_config(
    page_title="Business Impact Simulator",
    page_icon="💰",
    layout="wide"
)

# =========================================================
# PAGE HEADER
# =========================================================
st.title("Business Impact Simulator")

st.markdown("""
Estimate the potential financial impact of customer retention
campaigns using churn prediction insights generated by the
machine learning model.
""")

st.info(
    "This simulator provides estimated business projections based "
    "on user-defined assumptions and retention campaign scenarios."
)

# =========================================================
# INPUT SECTION
# =========================================================
st.markdown("---")

st.subheader("Simulation Inputs")

col1, col2 = st.columns(2)

with col1:

    at_risk_customers = st.number_input(
        "Number of At-Risk Customers",
        min_value=1,
        value=250,
        step=25
    )

    average_clv = st.number_input(
        "Average Customer Lifetime Value ($)",
        min_value=100.0,
        value=800.0,
        step=100.0
    )

with col2:

    intervention_cost = st.number_input(
        "Retention Cost per Customer ($)",
        min_value=1.0,
        value=150.0,
        step=10.0
    )

    success_rate = st.slider(
        "Retention Success Rate (%)",
        min_value=1,
        max_value=100,
        value=15
    )

# =========================================================
# CALCULATIONS
# =========================================================
customers_retained = round(
    at_risk_customers *
    (success_rate / 100)
)

estimated_revenue_retained = (
    customers_retained *
    average_clv
)

campaign_cost = (
    customers_retained *
    intervention_cost
)

estimated_net_gain = (
    estimated_revenue_retained -
    campaign_cost
)

if campaign_cost > 0:

    roi = (
        estimated_net_gain /
        campaign_cost
    ) * 100

else:

    roi = 0

# =========================================================
# FINANCIAL SUMMARY
# =========================================================
st.markdown("---")

st.subheader(
    "Financial Impact Summary"
)

col1, col2, col3 = st.columns(3)

with col1:

    st.metric(
        "Estimated Customers Retained",
        f"{customers_retained:,.0f}"
    )

with col2:

    st.metric(
        "Estimated Revenue Retained",
        f"${estimated_revenue_retained:,.0f}"
    )

with col3:

    st.metric(
        "Retention Campaign Cost",
        f"${campaign_cost:,.0f}"
    )

col4, col5 = st.columns(2)

with col4:

    st.metric(
        "Estimated Net Gain",
        f"${estimated_net_gain:,.0f}"
    )

with col5:

    st.metric(
        "Estimated ROI",
        f"{roi:.2f}%"
    )

# =========================================================
# EXECUTIVE INTERPRETATION
# =========================================================
st.markdown("---")

st.subheader(
    "Executive Interpretation"
)

if roi > 250:

    st.success(
        "The projected retention campaign demonstrates strong "
        "financial potential with significant estimated returns."
    )

elif roi > 100:

    st.info(
        "The campaign is projected to generate positive business "
        "value under the selected assumptions."
    )

elif roi > 0:

    st.warning(
        "The campaign remains profitable, although optimization "
        "of retention strategies may improve outcomes."
    )

else:

    st.error(
        "The current assumptions result in a negative estimated ROI."
    )
# =========================================================
# BUSINESS RECOMMENDATION
# =========================================================
st.markdown("---")

st.subheader(
    "Recommended Business Action"
)

if roi > 250:

    st.success(
        "The organization may consider aggressively targeting "
        "high-risk customers with personalized retention campaigns."
    )

elif roi > 100:

    st.info(
        "The projected returns justify moderate investment in "
        "customer retention initiatives."
    )

elif roi > 0:

    st.warning(
        "Retention efforts should focus on the highest-risk "
        "customer segments to maximize efficiency."
    )

else:

    st.error(
        "The current campaign assumptions should be re-evaluated "
        "before large-scale deployment."
    )

# =========================================================
# CALCULATION LOGIC
# =========================================================
st.markdown("---")

st.subheader(
    "Financial Estimation Logic"
)

st.markdown("""
- **Estimated Customers Retained**
  = At-Risk Customers × Retention Success Rate

- **Estimated Revenue Retained**
  = Customers Retained × Average Customer Lifetime Value

- **Retention Campaign Cost**
  = Customers Retained × Retention Cost per Customer

- **Estimated Net Gain**
  = Estimated Revenue Retained − Campaign Cost

- **Estimated ROI (%)**
  = (Estimated Net Gain ÷ Campaign Cost) × 100
""")

st.caption(
    "Financial estimates shown are simulation-based projections and may vary depending on real-world business conditions."
)